In [14]:
import torch

known_classes = 2 

targets = torch.tensor([2,2,3,1,0])
logits = torch.tensor([[-0.5535, -0.6662, -0.1914,  0.5350],
        [-0.3615, -0.6567, -0.0224,  0.5146],
        [-0.8029, -0.5689, -0.3258,  0.6984],
        [-0.9329, -0.4614, -0.4964,  0.8099],
        [-1.0794, -0.6220, -0.7531,  0.9719]])

print(targets.shape)
print(logits.shape)
mask = targets < known_classes
print(logits)
print(logits[mask])
print(logits[~mask])

print(logits[:3])


torch.Size([5])
torch.Size([5, 4])
tensor([[-0.5535, -0.6662, -0.1914,  0.5350],
        [-0.3615, -0.6567, -0.0224,  0.5146],
        [-0.8029, -0.5689, -0.3258,  0.6984],
        [-0.9329, -0.4614, -0.4964,  0.8099],
        [-1.0794, -0.6220, -0.7531,  0.9719]])
tensor([[-0.9329, -0.4614, -0.4964,  0.8099],
        [-1.0794, -0.6220, -0.7531,  0.9719]])
tensor([[-0.5535, -0.6662, -0.1914,  0.5350],
        [-0.3615, -0.6567, -0.0224,  0.5146],
        [-0.8029, -0.5689, -0.3258,  0.6984]])
tensor([[-0.5535, -0.6662, -0.1914,  0.5350],
        [-0.3615, -0.6567, -0.0224,  0.5146],
        [-0.8029, -0.5689, -0.3258,  0.6984]])
